# Generated by Django 5.1.4 on 2025-02-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0005_remove_programmerexpertise_image_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='programmerskill',
            constraint=models.UniqueConstraint(fields=('name', 'skill_level'), name='unique_name_skill_level'),
        ),
    ]
