# Generated by Django 5.1.4 on 2025-04-26 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_session', models.UUIDField(default=uuid.uuid4)),
                ('language', models.TextField(blank=True, null=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type_class', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='public', max_length=50)),
                ('class_title', models.CharField(blank=True, max_length=150, null=True)),
                ('educational_heading', models.TextField(blank=True, null=True)),
                ('educational_heading_file', models.FileField(upload_to='static/project/files')),
                ('price', models.BigIntegerField(default=0)),
                ('discount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('buffer_date', models.BigIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('time_line', models.TextField(blank=True, null=True)),
                ('is_tender', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects_by', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/project/image_project/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.educationproject')),
            ],
        ),
        migrations.CreateModel(
            name='TenderProject',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/tender/image')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_bid', models.BigIntegerField(default=0)),
                ('highest_bid', models.BigIntegerField(default=0)),
                ('language', models.TextField(blank=True, null=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('tender', 'مناقصه'), ('auction', 'مزایده')], default='tender', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tenders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.educationproject')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='projects.tenderproject')),
            ],
            options={
                'ordering': ['-amount'],
            },
            bases=('core.timestamp',),
        ),
    ]
