# Generated by Django 5.1.4 on 2025-05-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
