# Generated by Django 5.1.4 on 2025-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
