# Generated by Django 5.1.4 on 2025-05-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_bid_is_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='is_disabled',
            new_name='is_accepted',
        ),
    ]
