# Generated by Django 5.1.4 on 2025-02-18 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('programming_language', '0006_programmerskill_unique_name_skill_level'),
        ('projects', '0006_remove_educationpeoject_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderProject',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('highest_bid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tenders', to=settings.AUTH_USER_MODEL)),
                ('language', models.ManyToManyField(related_name='tender_language', to='programming_language.programmerskill')),
                ('skills', models.ManyToManyField(related_name='tender_skill', to='programming_language.programmerexpertise')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='projects.tenderproject')),
            ],
            options={
                'ordering': ['-amount'],
            },
            bases=('core.timestamp',),
        ),
    ]
