# Generated by Django 5.1.4 on 2025-05-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_is_disabled_bid_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationproject',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
