# Generated by Django 5.1.4 on 2025-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0006_programmerskill_unique_name_skill_level'),
        ('projects', '0007_tenderproject_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproject',
            name='language',
            field=models.ManyToManyField(related_name='tender_language', to='programming_language.programmerexpertise'),
        ),
        migrations.AlterField(
            model_name='tenderproject',
            name='skills',
            field=models.ManyToManyField(related_name='tender_skill', to='programming_language.programmerskill'),
        ),
    ]
