# Generated by Django 5.1.4 on 2025-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_tenderproject_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
