# Generated by Django 5.1.4 on 2025-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0006_programmerskill_unique_name_skill_level'),
        ('projects', '0009_tenderproject_start_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproject',
            name='language',
            field=models.ManyToManyField(related_name='tender_language', to='programming_language.programminglanguage'),
        ),
    ]
