# Generated by Django 5.1.4 on 2025-03-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_tenderproject_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
