# Generated by Django 5.1.4 on 2025-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_tenderproject_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tender/files'),
        ),
    ]
