# Generated by Django 5.1.4 on 2025-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_tenderproject_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='tender/image'),
        ),
    ]
