# Generated by Django 5.1.4 on 2025-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_tenderproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/tender/files'),
        ),
        migrations.AlterField(
            model_name='tenderproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/tender/image'),
        ),
    ]
