# Generated by Django 5.1.4 on 2025-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_tenderproject_file_alter_tenderproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproject',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=10), max_digits=10),
        ),
    ]
