# Generated by Django 5.1.4 on 2025-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_tenderproject_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproject',
            name='highest_bid',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='tenderproject',
            name='start_bid',
            field=models.IntegerField(default=0),
        ),
    ]
