# Generated by Django 5.1.4 on 2025-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_tenderproject_highest_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderproject',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
