# Generated by Django 5.1.4 on 2025-04-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0006_programmerskill_unique_name_skill_level'),
        ('projects', '0018_alter_tenderproject_highest_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderproject',
            name='file',
        ),
        migrations.CreateModel(
            name='EducationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_session', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
                ('type_class', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='public', max_length=50)),
                ('educational_heading', models.TextField(blank=True, null=True)),
                ('educational_heading_file', models.FileField(upload_to='static/project/files')),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('buffer_date', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/project/image_project')),
                ('time_line', models.TextField(blank=True, null=True)),
                ('is_tender', models.BooleanField(default=False)),
                ('expertise', models.ManyToManyField(related_name='project_expertise', to='programming_language.programmerexpertise')),
                ('language', models.ManyToManyField(related_name='project_language', to='programming_language.programminglanguage')),
                ('users', models.ManyToManyField(related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tenderproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.educationproject'),
        ),
        migrations.DeleteModel(
            name='EducationPeoject',
        ),
    ]
