# Generated by Django 5.1.4 on 2025-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_tenderproject_file_educationproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='mode',
            field=models.CharField(choices=[('tender', 'مناقصه'), ('auction', 'مزایده')], default='tender', max_length=50),
        ),
    ]
