# Generated by Django 5.1.4 on 2025-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_tenderproject_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationproject',
            name='class_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
