# Generated by Django 5.1.4 on 2025-04-09 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_educationproject_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationproject',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
