# Generated by Django 5.1.4 on 2025-04-12 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_educationproject_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
