# Generated by Django 5.1.4 on 2025-04-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderproject',
            name='image',
        ),
    ]
