# Generated by Django 5.1.4 on 2025-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_tenderproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/tender/image'),
        ),
    ]
