# Generated by Django 5.1.4 on 2025-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_tenderproject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='educationproject',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='educationproject',
            name='language',
        ),
        migrations.AddField(
            model_name='educationproject',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationproject',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
