# Generated by Django 5.1.4 on 2025-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_remove_educationproject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationproject',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
