# Generated by Django 5.1.4 on 2025-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_educationproject_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationproject',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
