# Generated by Django 5.1.4 on 2025-04-13 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_educationproject_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationproject',
            name='class_session',
            field=models.IntegerField(default=uuid.uuid4),
        ),
    ]
