# Generated by Django 5.1.4 on 2025-04-13 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_educationproject_class_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationproject',
            name='class_session',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
