# Generated by Django 5.1.4 on 2025-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_educationproject_class_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='tenderproject',
            name='language',
        ),
        migrations.AddField(
            model_name='tenderproject',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
