# Generated by Django 5.1.4 on 2025-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_tenderproject_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderproject',
            name='skills',
        ),
        migrations.AddField(
            model_name='tenderproject',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
