# Generated by Django 5.1.4 on 2025-03-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(upload_to='static/posts/images'),
        ),
    ]
