# Generated by Django 5.1.4 on 2025-03-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
