# Generated by Django 5.1.4 on 2025-04-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_liked_is_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/posts/file/'),
        ),
        migrations.CreateModel(
            name='PostsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ManyToManyField(related_name='user_post_list', to='post.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
