# Generated by Django 5.1.4 on 2025-04-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_posts_order_postgroup_delete_postslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.postgroup'),
        ),
    ]
