# Generated by Django 5.1.4 on 2025-04-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_posts_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
