# Generated by Django 5.1.4 on 2025-04-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_posts_group_postgroup_collection_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
