# Generated by Django 5.1.4 on 2025-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='media_type',
            field=models.CharField(default='picture', max_length=50),
        ),
    ]
