# Generated by Django 5.1.4 on 2025-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0006_debugsession_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
