# Generated by Django 5.1.4 on 2025-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0007_consultsession_title_debugsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
