# Generated by Django 5.1.4 on 2025-04-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0008_consultsession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='lnaguage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
