# Generated by Django 5.1.4 on 2025-04-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0009_consultsession_lnaguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='consultsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
