# Generated by Django 5.1.4 on 2025-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0010_consultsession_created_at_consultsession_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='is_realtime',
            field=models.BooleanField(default=True),
        ),
    ]
