# Generated by Django 5.1.4 on 2025-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0011_debugsession_is_realtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='is_realtime',
            field=models.BooleanField(default=True),
        ),
    ]
