# Generated by Django 5.1.4 on 2025-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0012_consultsession_is_realtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultsession',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
