# Generated by Django 5.1.4 on 2025-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0013_consultsession_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
