# Generated by Django 5.1.4 on 2025-04-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0014_consultsession_is_locked_debugsession_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultsession',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
