# Generated by Django 5.1.4 on 2025-04-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultHub', '0016_consultsession_is_rejected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultsession',
            old_name='lnaguage',
            new_name='language',
        ),
    ]
