# Generated by Django 5.1.4 on 2025-02-26 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0013_alter_customuser_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits.', regex='^09\\d{9}$')]),
        ),
    ]
