# Generated by Django 5.1.4 on 2025-03-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_alter_customuser_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_wallet',
            field=models.IntegerField(default=0, verbose_name='اعتبار بلاک شده'),
        ),
    ]
