# Generated by Django 5.1.4 on 2025-04-03 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0016_userbankcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankcards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
