# Generated by Django 5.1.4 on 2025-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0017_alter_userbankcards_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankcards',
            name='default_card',
            field=models.BooleanField(default=False),
        ),
    ]
