# Generated by Django 5.1.4 on 2025-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0018_userbankcards_default_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankcards',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
