# Generated by Django 5.1.4 on 2025-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0019_userbankcards_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
