# Generated by Django 5.1.4 on 2025-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0020_customuser_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='safe_withdraw',
            field=models.IntegerField(default=0, verbose_name='برداشت امن'),
        ),
    ]
