# Generated by Django 5.1.4 on 2025-05-19 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0022_requestpassowordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpassowordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_reset_password', to=settings.AUTH_USER_MODEL),
        ),
    ]
