# Generated by Django 5.1.4 on 2025-05-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0023_alter_requestpassowordreset_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestpassowordreset',
            old_name='is_used',
            new_name='is_verified',
        ),
    ]
