# Generated by Django 5.1.4 on 2025-06-03 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0024_rename_is_used_requestpassowordreset_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebuggerExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("passing_score", models.IntegerField()),
                ("time_limit_minutes", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DebuggerExamScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("passed", models.BooleanField(default=False)),
                ("answers", models.JSONField(default=dict)),
                (
                    "debugger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auths.debuggerexam",
                    ),
                ),
            ],
            options={"unique_together": {("debugger", "exam")},},
        ),
    ]
