# Generated by Django 5.1.4 on 2025-06-06 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0025_debuggerexam_debuggerexamscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(
                        10, "امتیاز نمیتواند بیشتر از 5 باشد"
                    )
                ],
            ),
        ),
    ]
