# Generated by Django 5.1.4 on 2025-04-19 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('factor_uuid', models.UUIDField(default=uuid.uuid4)),
                ('amount', models.IntegerField(default=0)),
                ('payemnt_status', models.CharField(choices=[('pending', 'در حال پردازش'), ('success', 'با موفقیت انجام شد'), ('failed', 'با خطا مواجه شد')], default='pending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithDrawFunds',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در حال پردازش'), ('success', 'با موفقیت انجام شد'), ('failed', 'با خطا مواجه شد')], default='pending', max_length=50)),
                ('bank_card_to_with_draw', models.CharField(default='', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdraw', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.timestamp',),
        ),
    ]
