# Generated by Django 5.1.4 on 2025-02-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionPayment',
        ),
    ]
