# Generated by Django 5.1.4 on 2025-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='session_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
