# Generated by Django 5.1.4 on 2025-03-29 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_delete_sessionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_uuid', models.UUIDField(default=uuid.UUID('7400762b-f8b0-4524-aaf6-ad50549909b0'))),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payemnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payments')),
            ],
        ),
    ]
