# Generated by Django 5.1.4 on 2025-03-30 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('f1a348f9-de0a-49e1-8a1e-1a0fe13a13a3')),
        ),
    ]
