# Generated by Django 5.1.4 on 2025-04-01 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('f397630f-4585-4799-87ae-63c0dae6bf22')),
        ),
    ]
