# Generated by Django 5.1.4 on 2025-04-03 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('607257c0-faa8-4129-bf85-77fe5fde5382')),
        ),
    ]
