# Generated by Django 5.1.4 on 2025-04-03 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('ed3f9045-da02-4839-80ec-e050345cb162')),
        ),
    ]
