# Generated by Django 5.1.4 on 2025-04-03 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('c42496a6-760a-4bab-bad1-308a8d9a9389')),
        ),
    ]
