# Generated by Django 5.1.4 on 2025-04-03 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('f243fc08-efeb-41e3-b42f-94226c9d4387')),
        ),
    ]
