# Generated by Django 5.1.4 on 2025-04-05 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('69c13c96-235e-4732-8547-216f296f8d27')),
        ),
    ]
