# Generated by Django 5.1.4 on 2025-04-05 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.UUID('d7e51d44-70e8-402c-bb24-c91864d340ea')),
        ),
    ]
