# Generated by Django 5.1.4 on 2025-04-05 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_factor_factor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
