# Generated by Django 5.1.4 on 2025-04-14 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        ('payments', '0012_alter_factor_factor_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithDrawFunds',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در حال پردازش'), ('success', 'با موفقیت انجام شد'), ('failed', 'با خطا مواجه شد')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdraw', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.timestamp',),
        ),
    ]
