# Generated by Django 5.1.4 on 2025-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_withdrawfunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawfunds',
            name='bank_card_to_with_draw',
            field=models.CharField(default='', max_length=16),
        ),
    ]
