# Generated by Django 5.1.4 on 2025-04-15 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        ('user_resume', '0010_userresume_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desciption', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfoli_image', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='UserPortfolioIage',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('image', models.ImageField(upload_to='static/user/profolio/')),
                ('user_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_resume.userportfolio')),
            ],
            bases=('core.timestamp',),
        ),
    ]
