# Generated by Django 5.1.4 on 2025-04-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        ('user_resume', '0011_userportfolio_userportfolioiage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPortfolioIage',
            new_name='UserPortfolioImage',
        ),
    ]
