# Generated by Django 5.1.4 on 2025-04-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0012_rename_userportfolioiage_userportfolioimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userportfolio',
            old_name='desciption',
            new_name='description',
        ),
    ]
