# Generated by Django 5.1.4 on 2025-04-15 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0013_rename_desciption_userportfolio_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userportfolioimage',
            name='image',
            field=models.ImageField(upload_to='static/user/portfolio/'),
        ),
        migrations.AlterField(
            model_name='userportfolioimage',
            name='user_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_resume.userportfolio'),
        ),
    ]
