# Generated by Django 5.1.4 on 2025-04-16 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        ('user_resume', '0014_alter_userportfolio_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobHistory',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('companyName', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('responsibilities', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_history', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.timestamp',),
        ),
    ]
