# Generated by Django 5.1.4 on 2025-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0015_userjobhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdegree',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
