# Generated by Django 5.1.4 on 2025-05-10 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        ('user_resume', '0016_userdegree_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForiegnLanguage',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('name', models.CharField(max_length=30)),
                ('rate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_foreign_language', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.timestamp',),
        ),
    ]
