# Generated by Django 5.1.4 on 2025-05-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0017_userforiegnlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforiegnlanguage',
            name='rate',
            field=models.BigIntegerField(default=0),
        ),
    ]
