# Generated by Django 5.1.4 on 2025-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_description_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='agreement',
            field=models.TextField(default=''),
        ),
    ]
