# Generated by Django 5.1.4 on 2025-04-30 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        ('questions', '0003_question_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCategoryQuestion',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AiCategoryQuestion',
            },
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='AiQuestion',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desription', models.TextField(blank=True, null=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to='static/ai_question/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.aicategoryquestion')),
            ],
            options={
                'db_table': 'AiQuestion',
            },
            bases=('core.timestamp',),
        ),
    ]
