# Generated by Django 5.1.4 on 2025-04-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timestamp_updated_at'),
        ('questions', '0004_aicategoryquestion_aiquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquestion',
            name='type',
        ),
        migrations.CreateModel(
            name='AiQuestionAnswer',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('answer', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(default='text', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.aiquestion')),
            ],
            options={
                'db_table': 'AiQuestionAnswer',
            },
            bases=('core.timestamp',),
        ),
    ]
