# Generated by Django 5.1.4 on 2025-04-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_aiquestion_type_aiquestionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_category', to='questions.aicategoryquestion'),
        ),
        migrations.AlterField(
            model_name='aiquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_answer', to='questions.aiquestion'),
        ),
    ]
