# Generated by Django 5.1.4 on 2025-04-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_aiquestion_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiquestion',
            old_name='desription',
            new_name='description',
        ),
    ]
