# Generated by Django 5.1.4 on 2025-04-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_rename_desription_aiquestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicategoryquestion',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
