# Generated by Django 5.1.4 on 2025-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_aicategoryquestion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestion',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aiquestionanswer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
