# Generated by Django 5.1.4 on 2025-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_aiquestion_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestionanswer',
            name='language_type',
            field=models.CharField(choices=[('both', 'both'), ('front-end', 'front-end'), ('back-end', 'back-end')], default='both', max_length=100),
        ),
    ]
