# Generated by Django 5.1.4 on 2025-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_aiquestionanswer_language_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestionanswer',
            name='language_type',
            field=models.CharField(choices=[('all', 'all'), ('front-end', 'front-end'), ('back-end', 'back-end'), ('ai', 'ai'), ('data-analyze', 'data-analyze')], default='all', max_length=100),
        ),
    ]
