# Generated by Django 5.1.4 on 2025-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_aiquestionanswer_language_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestion',
            name='answers',
            field=models.TextField(default=''),
        ),
    ]
