# Generated by Django 5.1.4 on 2025-05-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_aiquestion_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquestion',
            name='answers',
        ),
    ]
