# Generated by Django 5.1.4 on 2025-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_remove_aiquestion_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestionanswer',
            name='answers',
            field=models.TextField(default=''),
        ),
    ]
