# Generated by Django 5.1.4 on 2025-05-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_aiquestionanswer_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquestionanswer',
            name='answers',
        ),
    ]
