# Generated by Django 5.1.4 on 2025-05-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_remove_aiquestionanswer_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Interview',
        ),
        migrations.RemoveField(
            model_name='section',
            name='category',
        ),
        migrations.AddField(
            model_name='section',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='questions.interview'),
        ),
    ]
