# Generated by Django 5.1.4 on 2025-05-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_rename_category_interview_remove_section_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interview',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='section',
            name='interview',
        ),
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='questions.category'),
            preserve_default=False,
        ),
    ]
