# Generated by Django 5.1.4 on 2025-05-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_rename_interview_category_remove_section_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestion',
            name='priority',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
    ]
