# Generated by Django 5.1.4 on 2025-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_alter_aiquestion_priority_alter_section_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
