# Generated by Django 5.1.4 on 2025-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicategoryquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
