# Generated by Django 5.1.4 on 2025-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_aicategoryquestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicategoryquestion',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='/media/ai_question/'),
        ),
    ]
