# Generated by Django 5.1.4 on 2025-04-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_usercomments_commented_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
