# Generated by Django 5.1.4 on 2025-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_usercomments_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
