# Generated by Django 5.1.4 on 2025-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
